### PR TITLE
Feature/pathrendercondition

### PR DESCRIPTION
**Pull request by kaushalmall**
Fixed typo.

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
@kaushalmall can you resolve the conflict plzz?

**Comment by kaushalmall** [comment]
image

**Comment by davidjgonzalez** [comment]
i walked into that one

**Comment by davidjgonzalez** [comment]
@kaushalmall can you double-check, i think i merged this right.

**Comment by kaushalmall** [comment]
@davidjgonzalez the xml is gone from the page. 

https://adobe-consulting-services.github.io/acs-aem-commons/features/ui-widgets/path-rendercondition/index.html

**Comment by davidjgonzalez** [comment]
Clear your cache - it’s there.

Initial commit had the ‘’’ which didn’t work w github markdown

**Pull request merged**
