### PR TITLE
documentation updates for PR#2564

### PR DESCRIPTION
**Pull request by YegorKozlov**
Document support for context-aware configurations + misc doc updates.
https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2564

### CODE REVIEW

**Comment by YegorKozlov** [comment]
the  code from #2564 is in 5.0.6. Please push the docs to the web site.

**Comment by YegorKozlov** [comment]
@davidjgonzalez can you please push this PR to the web site?

**Comment by davidjgonzalez** [comment]
you got it!

**Comment by kwin** [comment]
@YegorKozlov This broke the thumbnail in https://adobe-consulting-services.github.io/acs-aem-commons/#features.

Screenshot 2021-07-21 at 09 26 07

**Pull request merged**
