### PR TITLE
Adding Documentation for Redirect Map Manager

### PR DESCRIPTION
**Pull request by klcodanr**
As requested by @justinedelson in #1145. Hopefully, it looks okay. I can't get Jekyll to run the site locally and when I look at the forked repo all of the CSS / JS paths are broken.

### CODE REVIEW

**Comment by justinedelson** [comment]
thanks @klcodanr . there was one minor formatting issue. no biggie. sorry to hear you can't run jekyll locally. are you using rvm?

**Comment by klcodanr** [comment]
No I'm using rbenv. Sorry I'm not overly experienced in Ruby:

```Dans-MacBook-Pro:adobe-consulting-services.github.io danklco$ bundle exec jekyll serve
rbenv: bundle: command not found

The `bundle' command exists in these Ruby versions:
  2.3.1```

**Comment by klcodanr** [comment]
BTW @justinedelson I just published a blog post about it just in case you all wanted to feature it: https://blogs.perficient.com/adobe/2017/12/07/mastering-aem-dispatcher-part-5-managing-redirects-like-a-master/

**Comment by badvision** [comment]
Were the comments in the readme.md helpful at all?  I was able to build the documentation after figuring out how to install the dependencies.

**Comment by klcodanr** [comment]
@badvision -- I'm using a mac. I did realize that I need to install bundler. So I installed that, but now it's mad that jekyll isn't installed and jekyll doesn't want to install because it want's ruby_dep which requires a different version of Ruby:

```Dans-MacBook-Pro:adobe-consulting-services.github.io danklco$ bundle exec jekyll serve
rbenv: bundle: command not found

The `bundle' command exists in these Ruby versions:
  2.3.1

Dans-MacBook-Pro:adobe-consulting-services.github.io danklco$ sudo gem install bundler
Password:
Fetching: bundler-1.16.0.gem (100%)
Successfully installed bundler-1.16.0
Parsing documentation for bundler-1.16.0
Installing ri documentation for bundler-1.16.0
Done installing documentation for bundler after 5 seconds
1 gem installed
Dans-MacBook-Pro:adobe-consulting-services.github.io danklco$ bundle exec jekyll serve
rbenv: jekyll: command not found

The `jekyll' command exists in these Ruby versions:
  2.3.1

Dans-MacBook-Pro:adobe-consulting-services.github.io danklco$ sudo gem install jekyll
ERROR:  Error installing jekyll:
	ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.
Dans-MacBook-Pro:adobe-consulting-services.github.io danklco$ bundle exec jekyll serve
rbenv: jekyll: command not found

The `jekyll' command exists in these Ruby versions:
  2.3.1```

**Comment by klcodanr** [comment]
Ah yep, there you go, I'd missed bundler. I'm used to doing things directly from the `jekyll` command. Thanks @badvision !

**Comment by ireasor** [comment]
@klcodanr so you're good now?  based on the email notifications, it sounded like you were still having trouble.

**Comment by klcodanr** [comment]
Yes I am, thanks. One of those situations where you figure out the problem 30 seconds after you hit send.

**Pull request merged**
